#!/usr/bin/env bash
# Generates stylesheets/_fonts.css from fonts/sd-sans/*.woff2
# Each font is embedded as a base64 data URI in @font-face rules.
# Run: bash scripts/generate-font-css.sh

set -euo pipefail

FONT_DIR="$(cd "$(dirname "$0")/.." && pwd)/fonts/sd-sans"
OUT="$(cd "$(dirname "$0")/.." && pwd)/stylesheets/_fonts.css"

cat > "$OUT" <<'HEADER'
/* Auto-generated by scripts/generate-font-css.sh — do not edit manually */
HEADER

declare -a VARIANTS=(
  "Normal:400:normal"
  "Normal-Italic:400:italic"
  "Medium:500:normal"
  "Medium-Italic:500:italic"
  "SemiBold:600:normal"
  "SemiBold-Italic:600:italic"
  "Bold:700:normal"
  "Bold-Italic:700:italic"
  "ExtraBold:800:normal"
  "ExtraBold-Italic:800:italic"
)

for entry in "${VARIANTS[@]}"; do
  IFS=':' read -r suffix weight style <<< "$entry"
  file="$FONT_DIR/sd-sans-${suffix}.woff2"
  if [ ! -f "$file" ]; then
    echo "Warning: $file not found, skipping" >&2
    continue
  fi
  b64=$(base64 < "$file" | tr -d '\n')
  cat >> "$OUT" <<EOF
@font-face {
  font-family: "sd sans";
  src: url("data:font/woff2;base64,${b64}") format("woff2");
  font-weight: ${weight};
  font-style: ${style};
  font-display: swap;
}
EOF
done

echo "Generated $OUT ($(wc -c < "$OUT" | tr -d ' ') bytes)"
